export default {
  LOADING: 'LOADING',
  INTRO: 'INTRO',
  SHOPPING_CART: 'SHOPPING_CART',
  NOTIFICATION: 'NOTIFICATION',
  ADMIN_LOGIN: 'ADMIN_LOGIN',
  ADMIN: 'ADMIN',
  PRODUCT: 'PRODUCT',
  SHOP_MENU: 'SHOP_MENU',
  SUPPORT: 'SUPPORT',
  CONTACT: 'CONTACT',
  SETTING: 'SETTING',
  REGISTER: 'REGISTER'
};
